apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-git-clone-success
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "Repo successfully cloned"
