apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  labels:
    app: hp-event-listener
  name: hp-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - name: hp-trigger
    interceptors:
      - ref:
          name: "cel"
        params:
        - name: "filter"
          value: "header.match('X-GitHub-Event', 'push') && body.ref == 'refs/heads/master' && body.repository.full_name == 'phemankita/hp-tekton-tutorial'"
    bindings:
      - ref: hp-trigger-binding
    template:
      ref: hp-trigger-template
